### PR TITLE
Create skeleton of blog feature

### LINKED ISSUE #19: [ENHANCEMENT] Add support for blog posts
Right now, it basically only works for episodes. But a podcast might have a blog as well, and want to have those posts.

At the minimum, need a section for blogs, including (possibly) their own RSS. Although I think that most folks would subscribe to just the main one.

Also need a template for blog posts.

Should possibly have a toggle in the `config.toml` to choose whether or not blog posts should be included on the home page along with episodes. Displaying blog posts interspersed with episodes will require some more logic on the part of the display.

### PR DESCRIPTION
**Pull request by mattstratton**
Fixes #19

This is a work in progress; still need to do a bunch of stuff:

- [ ] Make individual blog pages look nice
- [x] Tweak the row and grid layouts with more metadata (author, etc)
- [ ] Update the feed to work properly
- [x] Add "subscribe to blog" button on home page
- [x] Update `HEAD` to include blog rss instead of episode on blog-related pages
- [x] Update docs

Signed-off-by: Matt Stratton <matt.stratton@hey.com>

### CODE REVIEW

**Comment by mattstratton** [comment]
You can poke around (row view only right now but the code is in for grid) at https://deploy-preview-310--sample-castanet.netlify.app/blog/

**Comment by chrisreddington** [comment]
@mattstratton - Is there anything you'd like me to pick up from the to do list to help out? :)

**Comment by mattstratton** [comment]
>Is there anything you'd like me to pick up from the to do list to help out? :)

I'd say take any of them - just let me know which ones so we don't try to do it at the same time :)

**Comment by chrisreddington** [comment]
> > Is there anything you'd like me to pick up from the to do list to help out? :)
> 
> I'd say take any of them - just let me know which ones so we don't try to do it at the same time :)

Cool! I'll likely not have a chance to look before the weekend, but will drop a note as soon as I take a look :)

**Comment by chrisreddington** [comment]
@mattstratton  - I'm starting work on the metadata pieces

**Comment by chrisreddington** [comment]
@mattstratton - I'm also working on updating the HEAD, updating the episode feed to work properly and the subscribe to blog piece.

**Comment by chrisreddington** [comment]
> @mattstratton - I'm also working on updating the HEAD and the subscribe to blog piece.

That one is now done, so I believe the following 3 are left - 

-  Make individual blog pages look nice
  - I'm not the greatest UI guru, so i'll steer clear of this one 👍
-  Update the feed to work properly
  - I wasn't quite sure what this one meant, as the blog and episode feeds look to be working correctly from my local environment?
-  Update docs
  -  Happy to take this one, but wanted to make sure that we weren't going to add any additional frontmatter before starting to document.

**Comment by mattstratton** [comment]
>Update the feed to work properly

this just meant I haven't really looked at the feed to make sure that all the items are correct/include all the things that a "good" blog RSS feed should have. I have to check to see what those fields/content should be; the blog feed might be fine already!

**Comment by mattstratton** [comment]
I think we can open up a new issue for cosmetic enhancements for the individual blog posts and then this should be able to ship

**Comment by chrisreddington** [comment]
> I think we can open up a new issue for cosmetic enhancements for the individual blog posts and then this should be able to ship

Makes sense to me. In which case, I think that all the original items in the issue (aside from cosmetic enhancements) are complete? :) Thanks!

**Comment by mattstratton** [comment]
I'll merge this and some others and cut a release!

**Comment by chrisreddington** [comment]
> I'll merge this and some others and cut a release!

Great, thanks @mattstratton  - It's now in action over at https://www.cloudwithchris.com/ :) 

This allows me to merge my own blog/site into my podcast site, and have one central place to manage everything. On a related point to that, I've made a private change to my [own private fork ](https://github.com/chrisreddington/castanet-cloudwithchris) to show a parameter of "ShortBio" if it exists in the Guest/Host file, instead of the main content. 

The reason for that, is for example my own bio [shown here](https://www.cloudwithchris.com/host/chrisreddington/) is very long, and I'd like a shorter snippet elsewhere. I've been consistent on ShortBio across guests and hosts for consistency, so can propose that as a PR if it's a useful addition.

**Pull request merged**
