### PR TITLE
Add default site-wide og:image to config.toml param

### PR DESCRIPTION
**Pull request by rajeshduggal**
Add a default site wide og:image tag that can be
overridden in each episode.

See: https://gohugo.io/functions/param

Closes mattstratton/castanet#187

Signed-off-by: Rajesh Duggal <rajesh@duggalmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/mattstratton/castanet/188)

### CODE REVIEW

**Comment by rajeshduggal** [comment]
@mattstratton can this same technique be used for the "locale" and perhaps some other vars? Thoughts?

**Comment by mattstratton** [comment]
I'm trying to make sure I understand what this is doing - this means you do NOT want to use the hard-coded name for default, but be able to specify one?

**Comment by rajeshduggal** [comment]
@mattstratton can you confirm that currently with castanet when you visit the website's home page there is no og:image tag in the html.  So when people share a link to the website home page (or any other non-episode page) on facebook, facebook doesn't see an og:image and so it tries to guess which image to show in the posting.  Website owners should be able to specify a default website og:image tag, and that value should be overridden if an image is specified in each episode's web page.  Do you agree? And does this code make that happen?

**Comment by rajeshduggal** [comment]
@mattstratton let me know if you need additional clarity. Thanks!

**Comment by mattstratton** [comment]
Sorry for the delay on reviewing this - I'm going to try to puzzle through it in the next few days before merging.

**Comment by mattstratton** [comment]
I'm going to close this PR since things have drifted since it was submitted, and I will handle it in #187 which I need to get around to soon anyway :)

**Pull request closed without merging**
