### PR TITLE
Row layout improvements

### LINKED ISSUE #320: [BUG] - Row layout uses a different media player than episode pages
I don't know how/when this happened, but it's weird.

in `partials/row.html`:

```
<audio src="{{ $.Site.Params.media_prefix }}{{ . }}" preload="auto" />
```

in `episode/single.html`

```
          <audio id="player2" style="width: 100%" controls preload="none">
            <source src="{{ $.Site.Params.media_prefix }}{{ . }}" type="audio/mp3">
            </audio>
```

### LINKED ISSUE #357: [BUG] - Episode icon isn't centered
**Describe the bug**

You did fix the problem where the episode description text wasn't aligned with other episodes, but also the icon is not centered in the place where it is.  See this attached screenshot to get an idea.

At a minimum I think the description text should be centered with respect to the show icon and not have quite so much white space between the icon and the text.

Screen Shot 2021-04-07 at 6 33 35 PM

I don't know the right way to fix it, it just doesn't seem to look great the way it is right now.

### PR DESCRIPTION
**Pull request by mattstratton**
Change audio player to the proper one and remove some padding

Fixes #320
Fixes #357

Signed-off-by: Matt Stratton <matt.stratton@hey.com>

### CODE REVIEW

**Comment by ctindel** [comment]
But you see, look at how the example looks.  The tex that is there doesn't even take up all the space that exists.  The "read more" shouldn't start until the text has filled in the entire space next to the icon.  

Basically I'm left asking myself, why did it cut the text off and tell me to click a link to read more when there's all this dead space underneath that more text could fill in?

If the icon is smaller, the read more should start earlier, etc.

The logical part of my brain is telling me the text should be vertically centered around the icon but I'm not actually sure that would make it look better to be honest.

**Comment by ctindel** [comment]
Screen Shot 2021-04-07 at 9 35 05 PM

It just doesn't feel "responsive".  Same thing when I make it small, like these icons are way over to the left and a bunch of blank space on the right.  

Screen Shot 2021-04-07 at 9 35 49 PM

I kind of like how this podcast did it, where all the subscribe icons are fixed identical size.

https://www.letstalkaboutsets.com/subscribe/

**Comment by mattstratton** [comment]
If you wanted more text in the description, you can set a different value for `truncate` on the episode; right now it truncates at 600 characters by default, but that can be set differently. I suspect that the default `truncate` should be more than 600 characters to account for that whitespace.

For now, this is still going to be based around larger episode images until I can think of a way to make the layout more customizable :)

With regard to the CTA buttons being the same width when on the mobile view, that is definitely do-able with some media queries; I would say open a new issue for that one so that I can keep track of it.

**Comment by mattstratton** [comment]
Basically, there's a bunch of stuff I want to improve on the mobile display anyway (the episode images have padding on the left but not the right, so they don't look right) and I've been meaning to address that for a while :)

**Comment by ctindel** [comment]
Sounds good.  I will look forward to whatever changes you make around more compact episode listings and (hopefully!) embeddable anchor.fm players.

Just so you know why I think the episode listing should be more compact... there is already an episode details page where people can go if they want more info.  If you wanted some sort of reasonable hybrid, maybe the most recent episode is more verbose and the other episodes in the list are more compact.

**Comment by mattstratton** [comment]
I think we could make an alternate format of "compact"; removing the descriptions from the row layout is a pretty big breaking change (and for the show that I have which uses the row layout, I actually want them there).

I think it could be done to make a more compact layout.

TBH, everything you're describing as what you want the row layout to change to is actually accomplished with the grid layout (look at https://arresteddevops.com for an example; that site doesn't show all the host images in the jumbo but that's an choice we made; you can absolutely show all hosts in the jumbotron in the grid layout)

**Comment by ctindel** [comment]
I don't know that I would necessarily "remove the descriptions" as much as I would just make it show the image smaller and make everything take up less space in general.  The grid layout also doesn't show the player though right?  It would be awesome to be able to be able to have compact rows with small icons, a single line of description and an embedded player that way maybe 5 or 6 rows might fit on one page.

**Comment by mattstratton** [comment]
Yeah, I think what needs to happen is just add a totally different additional layout (so the choices might be `grid`, `row`, and `row-compact` or something.

I am definitely not against this idea, and there are quite a few things I have been meaning to refactor in the partials to make the layouts more portable, so I could totally take this on, just saying it likely won't be in the next few days (he says knowing he'll end up staying up all night coding this).

**Comment by ctindel** [comment]
LOL yeah i've had multiple 4am nights this week for the exact same reason.  :) Thanks.

**Comment by mattstratton** [comment]
I am going to merge this since the player fix needs to get in there; I think that the rest of the conversation goes into the feature request of `row-compact` as an additional layout option.

**Pull request merged**
