### PR TITLE
Adjust blog metadata, reverse order of posts, add subscribe to blog, update HEAD on appropriate pages and update REFERENCE.md

### PR DESCRIPTION
**Pull request by chrisreddington**
This PR adds a partial for blog metadata (very similar to episode metadata, but also has the Posted By item), and is leveraged across all blog instances for consisteny (instead of issets which were used in some places).

Also adjusted the content queries to be reversed, as they were showing the oldest blog posts first, rather than the newest.

Signed-off-by: Chris Reddington <791642+chrisreddington@users.noreply.github.com>

### CODE REVIEW

**Comment by chrisreddington** [comment]
@mattstratton - I've just updated the REFERENCE.md to contain a section for the blog archetype. One aspect that is worth a discussion, is how to handle the "Author" archetype. Right now, it's just plain text. I think for the first iteration that would work.

However, it got me thinking - do we want to map this back to either Host or Guest, so that we can link back to their page? Most likely host I imagine, as I'm not sure guests would be blogging on the podcast site? Reason I'm asking about which, is that I could see in the exampleSite that you're listed as a Host and a Guest, so I think hugo would handle that scenario well due to it being ambiguous about which one you're looking for.

**Comment by mattstratton** [comment]
FYI I've been watching all the PRs and issues as they come in! This is all awesome. I have a few personal things going on for the next few days (nothing bad, just personal distractions) and I won't be able to get these all reviewed likely until the end of the week. Didn't want y'all to think I was ignoring it!

**Comment by chrisreddington** [comment]
> FYI I've been watching all the PRs and issues as they come in! This is all awesome. I have a few personal things going on for the next few days (nothing bad, just personal distractions) and I won't be able to get these all reviewed likely until the end of the week. Didn't want y'all to think I was ignoring it!

Thanks @mattstratton, hope all is ok - Take care!

**Comment by mattstratton** [comment]
Hmm. It really depends on what you want to do with the "author" object - do you want to have a list of authors that will show all the posts by that author? I also wonder how likely on a podcast site it is that there are lots of authors (as opposed to a company blog or something). I would potentially see this as a possible thing:

1. "Author" is actually connected to a "host" page/object
2. On a host page, where there is the sidebar that shows "episodes hosted by so-and-so" there could be another list under that is "blog posts by so-and-so"

That sidebar can get really long; this is already the case though on a podcast with a lot of episodes (take a look at https://www.arresteddevops.com/host/mstratton/ to see what happens when a host has ~100 or so episodes lol)

**Comment by mattstratton** [comment]
I can probably merge this into my working branch, but I don't want to merge it just yet since there is a discussion happening in this PR right now :)

**Comment by chrisreddington** [comment]
> Hmm. It really depends on what you want to do with the "author" object - do you want to have a list of authors that will show all the posts by that author? I also wonder how likely on a podcast site it is that there are lots of authors (as opposed to a company blog or something). I would potentially see this as a possible thing:
> 
> 1. "Author" is actually connected to a "host" page/object
> 2. On a host page, where there is the sidebar that shows "episodes hosted by so-and-so" there could be another list under that is "blog posts by so-and-so"
> 
> That sidebar can get really long; this is already the case though on a podcast with a lot of episodes (take a look at https://www.arresteddevops.com/host/mstratton/ to see what happens when a host has ~100 or so episodes lol)
> 
> > **[Matt Stratton](/host/mstratton/)**Matt Stratton is a Transformation Specialist at Red Hat and a long-time member of the global DevOps community. Back in the day, his license plate actually said “DevOps”.
> > Matt has over 20 years of experience in IT operations, ranging from large financial institutions such as JPMorganChase to internet firms including Apartments.com. He is a sought-after speaker internationally, presenting at Agile, DevOps, and ITSM focused events, including DevOps Enterprise Summit, DevOpsDays, Interop, PINK, and others worldwide.

Definitely agree on the host being the "linking factor", as that's pretty much what I had in mind too! 

Not sure on the best solution to the sidebar piece. Part of me is leaning towards moving away from the sidebar, and bringing it into the main content, and having a view that utilises more screen real estate, and a similar idea for blogs. I was wondering if there could be some pagination of those, but pagination between two different archetypes sounds like a different challenge... :)

**Comment by chrisreddington** [comment]
Hey @mattstratton, hope all is doing ok! Just wanted to check on how we are looking on these PRs? Particularly keen on the blog one moving forwards, so that I can merge my blog into my podcast site 🙂 thanks!

**Comment by mattstratton** [comment]
Yes! Sorry, I moved house last week and I'm still getting my workstation all set up 😂

I'll go through all of these in the next day or two and get things done!

**Comment by chrisreddington** [comment]
> Yes! Sorry, I moved house last week and I'm still getting my workstation all set up 😂
> 
> I'll go through all of these in the next day or two and get things done!

Congratulations :) Hope it all went well - Thank you!

**Comment by mattstratton** [comment]
I'm going to merge this into my blog feature branch, to keep things easier to chase down.

**Pull request merged**
