### PR TITLE
Work towards links in footer

### PR DESCRIPTION
**Pull request by chrisreddington**
This PR is a work in progress to address #51 

@mattstratton  - I have the logic in place to generate the links in the footer, as suggested from the above issue. However, i'm struggling to get the CSS to display the list horizontally - No matter what i've tried, it doesn't seem to address the ul element. Would appreciate some support/pointers on that bit, and then I think we can merge and close?

As an aside, I did wonder from that issue whether there needed to be so many checks on whether to display the links. Display links in the footer could be a nice extra for any theme/combination, unless I'm missing something there?

### CODE REVIEW

**Comment by mattstratton** [comment]
The main reason I was saying to not display links in the footer if the sidebar is active is just to not have redundant content; it's theoretically possible that having the same list of links on a page would look like "stuffing" to search engines, etc, but I don't know if that's still a thing :)

**Comment by chrisreddington** [comment]
Ah, gotcha - that makes sense! In which case, if SEO is the concern, perhaps there could be a consideration on using this GItHub action to validate PRs? I've been wondering about adopting this for the theme that I mentioned I'm building in the other issue.

https://github.com/GoogleChrome/lighthouse-ci

**Comment by mattstratton** [comment]
I think that action would be helpful and I might try it - although we have to see how to make it work with the full matrix (various combos of row/grid, etc)

**Comment by mattstratton** [comment]
I'll open a new issue for adding the Lighthouse stuff to the theme build tests; first glance is that getting the hugo build to work with their action might be tough but worth investigating!

**Comment by mattstratton** [comment]
Opened #318 for this :)

**Comment by mattstratton** [comment]
Also, I could be convinced to have the footer links display even with the sidebar enabled.

**Comment by mattstratton** [comment]
The footer links don't look right; need to see what's up (also they need to be styled better)

image

**Pull request closed without merging**
