### PR TITLE
Add optional explicit for the feed itself since seems itunes wants this

### PR DESCRIPTION
**Pull request by alexmurray**
When submitting my podcast to itunes, it kept reporting the feed was invalid since it did not have a top-level explicit tag.

So this adds an option to specify it and will only be included if specified to make sure existing configurations do not break.

---
This change is [Reviewable](https://reviewable.io/reviews/mattstratton/castanet/196)

### CODE REVIEW

**Comment by alexmurray** [comment]
See https://discussions.apple.com/thread/7742886 for a similar issue

**Comment by alexmurray** [comment]
This commit is actually signed - seemed the GPG bot was too early and checked it before I had uploaded my public key to github.

**Comment by rajeshduggal** [comment]
The code already adds an this tag into the RSS file, doesn't it?
https://github.com/mattstratton/castanet/blob/master/layouts/section/episode.rss.xml#L96
And I see the tag in my RSS file already too...
https://khabardaarpodcast.com/episode/index.xml

**Comment by alexmurray** [comment]
That tag is per episode, this change adds an optional tag to the overall feed itself.

**Pull request merged**
